### ISSUE TITLE
Missing "swupd"

### ISSUE THREAD

**Issue by Aqua1ung** [clearfraction/docs#1]
Looks like the [code to "install GCC and third-party libraries"](https://github.com/clearfraction/docs/blob/main/README.md#how-to-build-software-using-clear-fraction-libraries-like-x264-x265-or-cuda) is missing the `swupd` keyword in the commands for codecs installation.

**Comment by paulcarroty** [comment]
Yeah, thx. Going to fix it & add direct link from `/distribution`.
